const fs = require('fs');
let content = fs.readFileSync('src/pages/Impex.tsx', 'utf8');

content = content.replace(
  "" + "import type { ImpexResponse } from '../types/impex';",
  "" + "import type { ImpexResponse, SavedImpexPart } from '../types/impex';"
);

const savedPartsComponent = [
  "const SavedPartsTab = () => {",
  "  const [savedParts, setSavedParts] = useState<SavedImpexPart[]>([]);",
  "  const [loading, setLoading] = useState(true);",
  "  const [error, setError] = useState<string | null>(null);",
  "",
  "  const fetchSavedParts = async () => {",
  "    try {",
  "      setLoading(true);",
  "      setError(null);",
  "      const res = await impexService.getSavedParts();",
  "      if (res.success) {",
  "        setSavedParts(res.data);",
  "      } else {",
  "        setError('Respuesta no exitosa de la API');",
  "      }",
  "    } catch (err: any) {",
  "      setError(err.message || 'Error al obtener los repuestos guardados');",
  "    } finally {",
  "      setLoading(false);",
  "    }",
  "  };",
  "",
  "  useEffect(() => {",
  "    fetchSavedParts();",
  "  }, []);",
  "",
  "  if (loading) {",
  "    return (",
  "      <div className=\"flex items-center justify-center min-h-[400px]\">",
  "        <div className=\"animate-spin rounded-full h-10 w-10 border-t-2 border-b-2 border-kawa-green\"></div>",
  "      </div>",
  "    );",
  "  }",
  "",
  "  if (error) {",
  "    return (",
  "      <div className=\"p-4 bg-red-900/40 border border-red-800 rounded-lg text-red-400\">",
  "        {error}",
  "      </div>",
  "    );",
  "  }",
  "",
  "  return (",
  "    <div className=\"bg-kawa-gray rounded-xl border border-gray-800 overflow-hidden shadow-sm\">",
  "      <div className=\"p-4 border-b border-gray-800 bg-[#2a2a2a] flex justify-between items-center\">",
  "        <h2 className=\"text-lg font-semibold text-white\">Piezas en Base de Datos</h2>",
  "        <div className=\"flex items-center gap-4\">",
  "          <span className=\"bg-[#1e1e1e] text-gray-400 text-xs px-2 py-1 rounded border border-gray-700\">",
  "            {savedParts.length} guardados",
  "          </span>",
  "          <button ",
  "            onClick={fetchSavedParts}",
  "            className=\"text-gray-400 hover:text-white transition-colors\"",
  "            title=\"Recargar\"",
  "          >",
  "            <svg className=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">",
  "              <path strokeLinecap=\"round\" strokeLinejoin=\"round\" strokeWidth={2} d=\"M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15\" />",
  "            </svg>",
  "          </button>",
  "        </div>",
  "      </div>",
  "      {savedParts.length > 0 ? (",
  "        <div className=\"overflow-x-auto\">",
  "          <table className=\"w-full\">",
  "            <thead className=\"bg-[#1a1a1a] border-b border-gray-800\">",
  "              <tr className=\"text-left text-gray-400 text-xs\">",
  "                <th className=\"p-4 font-semibold uppercase tracking-wider\">Parte</th>",
  "                <th className=\"p-4 font-semibold uppercase tracking-wider\">Nombre</th>",
  "                <th className=\"p-4 font-semibold uppercase tracking-wider\">Marca</th>",
  "                <th className=\"p-4 font-semibold uppercase tracking-wider\">Costo base</th>",
  "                <th className=\"p-4 font-semibold uppercase tracking-wider\">P. Venta (COP)</th>",
  "                <th className=\"p-4 font-semibold uppercase tracking-wider\">Creado</th>",
  "              </tr>",
  "            </thead>",
  "            <tbody className=\"bg-kawa-gray divide-y divide-gray-800\">",
  "              {savedParts.map(part => (",
  "                <tr key={part.id} className=\"hover:bg-[#2a2a2a] transition-colors\">",
  "                  <td className=\"p-4 whitespace-nowrap text-sm font-medium text-white\">{part.part_no}</td>",
  "                  <td className=\"p-4 text-sm text-gray-400 max-w-xs truncate\" title={part.name_es || part.name_en || part.name_ja || ''}>",
  "                    {part.name_es || part.name_en || part.name_ja}",
  "                  </td>",
  "                  <td className=\"p-4 whitespace-nowrap text-sm text-gray-400\">{part.mark}</td>",
  "                  <td className=\"p-4 whitespace-nowrap text-sm text-gray-400 font-mono\">¥ {part.price_yen?.toLocaleString() ?? 0}</td>",
  "                  <td className=\"p-4 whitespace-nowrap text-sm font-semibold text-kawa-green\">",
  "                    $ {part.kawadojo_price?.toLocaleString('es-CO', { maximumFractionDigits: 0 })}",
  "                  </td>",
  "                  <td className=\"p-4 whitespace-nowrap text-sm text-gray-500\">",
  "                    {part.created_at ? new Date(part.created_at).toLocaleDateString('es-CO') : '---'}",
  "                  </td>",
  "                </tr>",
  "              ))}",
  "            </tbody>",
  "          </table>",
  "        </div>",
  "      ) : (",
  "        <div className=\"p-10 text-center flex flex-col items-center\">",
  "           <svg className=\"w-16 h-16 text-gray-700 mb-4\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">",
  "             <path strokeLinecap=\"round\" strokeLinejoin=\"round\" strokeWidth={1.5} d=\"M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4\" />",
  "           </svg>",
  "           <h3 className=\"text-white font-bold text-lg\">No hay piezas guardadas</h3>",
  "           <p className=\"text-gray-500 mt-2\">Usa la pestaña de búsqueda para cotizar y guardar repuestos.</p>",
  "        </div>",
  "      )}",
  "    </div>",
  "  );",
  "};"
].join('\n');

content = content.replace('const Impex: React.FC = () => {', savedPartsComponent + '\nconst Impex: React.FC = () => {');

const placeholder = [
  '<div className="bg-kawa-gray border border-gray-800 rounded-xl p-10 shadow-sm flex flex-col items-center justify-center min-h-[400px]">',
  '          <svg className="w-16 h-16 text-gray-700 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">',
  '            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4" />',
  '          </svg>',
  '          <h2 className="text-xl font-bold text-white mb-2">Base de Datos Local</h2>',
  '          <p className="text-gray-400 text-center max-w-md">',
  '            Próximamente integraremos aquí tu propio inventario consultando directamente las piezas guardadas en la base de datos de Kawadojo.',
  '          </p>',
  '        </div>'
].join('\n');

content = content.replace(placeholder, '<SavedPartsTab />');

fs.writeFileSync('src/pages/Impex.tsx', content, 'utf8');
console.log('done');
